
services:
  frontend:
    build:
      context: .
      dockerfile: /spa_front/Dockerfile
    container_name: spa_front
    image: spa_front:latest
    ports:
      - "3000:4000"   # local:container
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: /spa_back/Dockerfile
    container_name: spa_back
    image: spa_back:latest
    ports:
      - "3001:4001"
    environment:
      - DATABASE_URL=postgres://app:!ChangeMe!@db:5432/app
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: spa_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

volumes:
  pgdata:
